### ISSUE TITLE
Add MIT Licence

### ISSUE THREAD

**Issue by chainwhisper** [nezza/DexVault#1]
Hello,

I am reviewing your solution and really like it. Can you add MIT license as required in the competition: https://community.binance.org/t/binance-dex-coding-competition-starts-now/837

Thanks

**Comment by nezza** [comment]
Hi @huangsuyu,

Thanks for the feedback!
I've listed the license in the README.md, but now also added it into a LICENSE file and adjusted the Github indicated license: 1d9abf11471119827ffb1f725b11a672edc1d455

Thanks,
Thomas

**Comment by chainwhisper** [comment]
looks great!
